"""Configuration module for IsraelGPT."""

from .settings import (
    TOKEN,
    AUTO_ROLE_ID,
    GEM_ROLE_ID,
    GEM_TRIGGER_PHRASE,
    AUDIT_LOG_CHANNEL_ID,
    DEFAULT_VOICE_CHANNEL_IDS,
    DEFAULT_PRIVATE_VOICE_LOBBY_ID,
    VOICE_TRANSCRIBE_INTERVAL,
    GUILD_CONFIG_PATH,
    PRIMARY_GUILD_ID,
    MARKETPLACE_CHANNEL_ID,
    MARKETPLACE_STAFF_ROLE_IDS,
    GROQ_API_KEY,
)

from .guild_config import (
    GuildSettings,
    guild_settings,
    load_guild_configs,
    save_guild_configs,
    get_guild_settings,
    get_auto_role_id,
    get_gem_role_id,
    get_gem_trigger_phrase,
    get_audit_log_channel_id,
    get_voice_channel_ids,
    get_private_voice_lobby_id,
)

__all__ = [
    "TOKEN",
    "AUTO_ROLE_ID",
    "GEM_ROLE_ID",
    "GEM_TRIGGER_PHRASE",
    "AUDIT_LOG_CHANNEL_ID",
    "DEFAULT_VOICE_CHANNEL_IDS",
    "DEFAULT_PRIVATE_VOICE_LOBBY_ID",
    "VOICE_TRANSCRIBE_INTERVAL",
    "GUILD_CONFIG_PATH",
    "PRIMARY_GUILD_ID",
    "MARKETPLACE_CHANNEL_ID",
    "MARKETPLACE_STAFF_ROLE_IDS",
    "GROQ_API_KEY",
    "GuildSettings",
    "guild_settings",
    "load_guild_configs",
    "save_guild_configs",
    "get_guild_settings",
    "get_auto_role_id",
    "get_gem_role_id",
    "get_gem_trigger_phrase",
    "get_audit_log_channel_id",
    "get_voice_channel_ids",
    "get_private_voice_lobby_id",
]
